#!/usr/bin/env bash
#
# clean.sh - remove the build artifacts of this SDK project (no_serail).
#
# Only generated files are removed. Sources, *.cmake.in templates and documents
# are kept. Everything removed here is recreated by re-running cmake.
#
# Usage:
#   ./clean.sh          clean after confirmation
#   ./clean.sh -y       clean without asking
#   ./clean.sh -n       dry run, only print what would be removed
#   ./clean.sh -h       show this help
#
set -uo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Build output directories.
BUILD_DIRS=(build build_sdk out cmake-build cmake-build-debug cmake-build-release)

# CMake caches, in case the project was configured in-source.
CACHE_FILES=(CMakeCache.txt cmake_install.cmake compile_commands.json Makefile
             install_manifest.txt CTestTestfile.cmake)
CACHE_DIRS=(CMakeFiles Testing)

# Files generated by configure_file() into the source tree.
GENERATED_FILES=(cmake/zvision_sdkConfig.cmake cmake/zvision_sdkConfigVersion.cmake
                 sdk/include/version.h)

usage() {
    sed -n '3,13p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

DRY_RUN=0
YES=0
while [ $# -gt 0 ]; do
    case "$1" in
        -n|--dry-run) DRY_RUN=1 ;;
        -y|--yes)     YES=1 ;;
        -h|--help)    usage; exit 0 ;;
        *)            echo "unknown option: $1" >&2; usage; exit 1 ;;
    esac
    shift
done

targets=()
for d in "${BUILD_DIRS[@]}"; do
    [ -d "$DIR/$d" ] && targets+=("$DIR/$d")
done
for f in "${CACHE_FILES[@]}"; do
    [ -e "$DIR/$f" ] && targets+=("$DIR/$f")
done
for d in "${CACHE_DIRS[@]}"; do
    [ -d "$DIR/$d" ] && targets+=("$DIR/$d")
done
for f in "${GENERATED_FILES[@]}"; do
    [ -e "$DIR/$f" ] && targets+=("$DIR/$f")
done

# Stray object files / libraries left in the source tree (build dirs pruned).
prune=()
for d in "${BUILD_DIRS[@]}"; do
    prune+=(-name "$d" -o)
done
prune+=(-name .git)
while IFS= read -r f; do
    targets+=("$f")
done < <(find "$DIR" \( "${prune[@]}" \) -prune -o -type f \
         \( -name '*.o' -o -name '*.obj' -o -name '*.a' -o -name '*.lib' \
            -o -name '*.so' -o -name '*.so.*' -o -name '*.dylib' \
            -o -name '*.gcda' -o -name '*.gcno' \) -print)

if [ ${#targets[@]} -eq 0 ]; then
    echo "Nothing to clean."
    exit 0
fi

echo "Will remove ${#targets[@]} entries:"
for t in "${targets[@]}"; do
    echo "  ${t#$DIR/}"
done

if [ "$DRY_RUN" -eq 1 ]; then
    echo
    echo "[dry-run] Nothing was deleted."
    exit 0
fi

if [ "$YES" -eq 0 ]; then
    printf '\nContinue? [y/N] '
    read -r answer
    case "$answer" in
        y|Y|yes) ;;
        *) echo "Aborted."; exit 1 ;;
    esac
fi

for t in "${targets[@]}"; do
    rm -rf -- "$t"
done

echo "Done. Removed ${#targets[@]} entries."
